// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assiment_efcore_4444;

#nullable disable

namespace assimentefcore4444.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20260509232026_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("assiment_efcore_4444.Customer", b =>
                {
                    b.Property<int>("customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nationalid")
                        .HasColumnType("int");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phone")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerid");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("assiment_efcore_4444.Manger", b =>
                {
                    b.Property<int>("mangerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mangerid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("phoneNumber")
                        .HasColumnType("int");

                    b.HasKey("mangerid");

                    b.ToTable("manger");
                });

            modelBuilder.Entity("assiment_efcore_4444.Transaction", b =>
                {
                    b.Property<int>("transactionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transactionid"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("accountid")
                        .HasColumnType("int");

                    b.Property<DateTime>("transactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("transactiontype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("transactionid");

                    b.HasIndex("accountid");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("assiment_efcore_4444.account", b =>
                {
                    b.Property<int>("AcountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcountNumber"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branchcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchid")
                        .HasColumnType("int");

                    b.Property<int>("currentBalance")
                        .HasColumnType("int");

                    b.Property<DateTime>("openingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AcountNumber");

                    b.HasIndex("branchid");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("assiment_efcore_4444.branch", b =>
                {
                    b.Property<int>("Branchcoude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Branchcoude"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mangerid")
                        .HasColumnType("int");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Branchcoude");

                    b.HasIndex("mangerid")
                        .IsUnique();

                    b.ToTable("branches");
                });

            modelBuilder.Entity("assiment_efcore_4444.customerAcount", b =>
                {
                    b.Property<int>("customerid")
                        .HasColumnType("int");

                    b.Property<int>("accountid")
                        .HasColumnType("int");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OwnerShipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerShipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerid", "accountid");

                    b.HasIndex("accountid");

                    b.ToTable("customerAcount");
                });

            modelBuilder.Entity("assiment_efcore_4444.Transaction", b =>
                {
                    b.HasOne("assiment_efcore_4444.account", "account")
                        .WithMany("Transaction")
                        .HasForeignKey("accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("assiment_efcore_4444.account", b =>
                {
                    b.HasOne("assiment_efcore_4444.branch", "branch")
                        .WithMany("accounts")
                        .HasForeignKey("branchid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("assiment_efcore_4444.branch", b =>
                {
                    b.HasOne("assiment_efcore_4444.Manger", "Manger")
                        .WithOne("branch")
                        .HasForeignKey("assiment_efcore_4444.branch", "mangerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manger");
                });

            modelBuilder.Entity("assiment_efcore_4444.customerAcount", b =>
                {
                    b.HasOne("assiment_efcore_4444.account", "account")
                        .WithMany()
                        .HasForeignKey("accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assiment_efcore_4444.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("assiment_efcore_4444.Manger", b =>
                {
                    b.Navigation("branch")
                        .IsRequired();
                });

            modelBuilder.Entity("assiment_efcore_4444.account", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("assiment_efcore_4444.branch", b =>
                {
                    b.Navigation("accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
